Repository onetalksoft/fastify-template, pull requests merged in 2021-10, with the labels that each got.

#1 initialized fastify
  index.js
  package-lock.json
  package.json
Labels: hacktoberfest-accepted

#3 created readme and contributing files
  CONTRIBUTING.md
  README.md
Labels: documentation, hacktoberfest-accepted, hacktoberfest

#4 modified
  index.js
  package-lock.json
  package.json
Labels: hacktoberfest-accepted, hacktoberfest

#5 revamped whole api endpoints
  User.js
  index.js
  package-lock.json
  package.json
Labels: enhancement, hacktoberfest-accepted, hacktoberfest

#6 Updated readme
  README.md
Labels: documentation, hacktoberfest-accepted

#7 Updated doc
  README.md
Labels: documentation, hacktoberfest-accepted

#8 added links
  README.md
Labels: hacktoberfest-accepted, hacktoberfest

#10 Update CONTRIBUTING.md
  CONTRIBUTING.md
Labels: hacktoberfest-accepted, hacktoberfest
