Repository onetalksoft/fastify-template, pull requests merged in 2022-10, with the labels that each got.

#13 Added Dockerfile and .dockerignore
  .dockerignore
  Dockerfile
  README.md
Labels: hacktoberfest-accepted, hacktoberfest

#16 Update index.js
  index.js
Labels: hacktoberfest-accepted, hacktoberfest

#18 updated documentation
  README.md
Labels: documentation, hacktoberfest-accepted, hacktoberfest

#20 added mild update README.md
  README.md
Labels: documentation, hacktoberfest-accepted, hacktoberfest

#21 Updated index.js
  index.js
Labels: enhancement, hacktoberfest-accepted, hacktoberfest

#23 Update README.md
  README.md
Labels: documentation, hacktoberfest-accepted, hacktoberfest

#24 added schema docs User.js
  User.js
Labels: documentation, hacktoberfest-accepted, hacktoberfest
